// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef DRIVE_H
#define DRIVE_H

#include "Commands/PIDSubsystem.h"
#include "WPILib.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class Drive: public PIDSubsystem {
 public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	std::shared_ptr<SpeedController> driveMotor1;
	std::shared_ptr<SpeedController> driveMotor2;
	std::shared_ptr<SpeedController> driveMotor3;
	std::shared_ptr<SpeedController> driveMotor4;
	std::shared_ptr<RobotDrive> robotDrive41;
	std::shared_ptr<SpeedController> driveMotor5;
	std::shared_ptr<SpeedController> driveMotor6;
	std::shared_ptr<RobotDrive> robotDrive21;
	std::shared_ptr<Encoder> encoder2;
	std::shared_ptr<Encoder> encoder3;
	std::shared_ptr<Encoder> encoder4;
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	Drive();
	double ReturnPIDInput();
	void UsePIDOutput(double output);
	void InitDefaultCommand();
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
};

#endif
